# Given two homogeneous Markov processes with (possibly truncated) transition
# probabilities P and Q respectively, which are defined on the same state
# space, simulate a path of length k from the process generated by P, and find
# the corresponding maximal coupling probability between this path and one
# generated from Q
function simulate_path_coupling(k::Integer, P::Array{Float64,2}, Q::Array{Float64,2})::Float64
    size(P) ≠ size(Q) && throw(DimensionMismatch("P and Q do not have the same state space"))
    size(P, 1) ≠ size(P, 2) && throw(DimensionMismatch("P and Q are not square matrices"))
end